### ISSUE TITLE
[PE-D][Tester E] The add command allows invalid email format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-1/tp#127]
![image.png](https://raw.githubusercontent.com/wolffe88/ped/main/files/8f3ae89a-d6b9-41f2-ac70-3bf9e5c75928.png)

I was able to add johnd@ww as an email eventhough it does not comply with the IETF standards. If not fixed invalid email could plague the whole program especially if users are prone to typos.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wolffe88/ped#6

**Comment by tanjieling0** [comment]
FROM GUIDE TO PE-D BUG FIXES:
Accepting seemingly 'unsuitable' values for an input (e.g., accepting numbers for a person name, empty value as a parameter):
This is not considered 'incorrect' (giving more freedom to the user is not necessarily incorrect) unless those unsuitable values causes the application to misbehave.

**Comment by tanjieling0** [comment]
I don't this we can fix this, but I'm not sure

**Comment by shaunlxw** [comment]
I also don't think we can fix this... will add a note in add and edit command that mentions that NetConnect does not do validation check for the domain part of the email.
