### ISSUE TITLE
[PE-D][Tester B] Wrong example provided for add command in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F12-1/tp#141]
**Steps to Reproduce:** 
1. Paste this whole example into the command Box
![Screenshot 2024-04-05 at 4.31.08 PM.png](https://raw.githubusercontent.com/gauravuj/ped/main/files/60a9d239-b1aa-4184-a350-58820a4cbf7d.png)

**Expected:**  Should **not** show an error as it is included in the User Guide

**Actual:** Shows an `error` 
![Screenshot 2024-04-05 at 4.30.09 PM.png](https://raw.githubusercontent.com/gauravuj/ped/main/files/61e1fb9b-9477-429b-b1aa-ecdc97dd5b47.png)

**Also**, the examples are too lengthy. Maybe try making it shorter.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: gauravuj/ped#3

**Comment by tanjieling0** [comment]
similar to the other issue but the other one needs update for warning message, this one updates the UG
