### ISSUE TITLE
[PE-D][Tester A] I can put two TOS but it only stores the latest one

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-1/tp#147]
The add command can take in two TOS fields but only accepts the last one:

![image.png](https://raw.githubusercontent.com/Alteqa/ped/main/files/f934d7a9-6acc-4360-bb56-e1beae456bc3.png)

![image.png](https://raw.githubusercontent.com/Alteqa/ped/main/files/5a7bf6c2-9223-4bdc-945a-533292cbd36b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Alteqa/ped#7

**Comment by tanjieling0** [comment]
similar to the duplicate role bug, don't think we can change but can document it in the UG

**Comment by purivirakarin** [comment]
we can handle this using `argMultimap.verifyNoDuplicatePrefixesFor`

**Comment by purivirakarin** [comment]
According to prof, "While this sounds like a genuine oversight, as the current behavior is not strictly incorrect, I'm afraid it doesn't pass the eligibility test for 'allowed' during the feature freeze. On a somewhat related note, this behavior used to be a deliberate optimization in an earlier version of AB3. That is, this behavior allows users to quickly retype a field they mistyped earlier in the command, which may be faster than navigating back to the place where the typo is and correcting it. So, this 'feature' was provided as a way for users to rectify mistakes faster. So, if you feel this feature can be useful for that purpose, you can present it as an 'experimental' feature enabled only for a few selected commands."

This issue can be closed.
