### ISSUE TITLE
[PE-D][Tester E] CSV fields and data mismatched

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-1/tp#159]
![image.png](https://raw.githubusercontent.com/wolffe88/ped/main/files/739a3054-958c-405e-b30c-26a9c6ae3e55.png)

The prooduct field should not have C++, the preference field should not have python and TOS should not have eggs.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wolffe88/ped#12

**Comment by shaunlxw** [comment]
Closed by #196.
