### ISSUE TITLE
[PE-D][Tester E] Lack of information on usage

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-1/tp#163]
![image.png](https://raw.githubusercontent.com/wolffe88/ped/main/files/255133c6-05f6-4769-8e46-f730bbdb67cf.png)

What will the notification look like and how do I know if it is going to work?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: wolffe88/ped#13

**Comment by tanjieling0** [comment]
move to future implementation / remove
